### ISSUE TITLE
Umbrella issue: Bucket#1: Board Definitions / APIs

### ISSUE THREAD

**Issue by krook** [ClusterDuck-Protocol/ClusterDuck-Protocol#341]
# Board definitions APIs

As CDP developer I want to update to update CDP supported boards more easily, so I can rapidly test new boards or port CDP to new hardware.

Currently, we have `src/include/boards/` folder which has 14 different board definitions. Many of these boards are no longer available and probably will no longer compile with CDP latest version.

Additionally, `cdpcfg.h` which includes the board definition headers (from the boards folder) could be simplified.
We can remove all the conditional compilation directives, by defining the ARDUINO board definition string in each individual board headers.

Finally, we should not default to any boards when building CDP. Instead we can error out of the compilation and warn the developer that their board is not supported.

# Acceptance criteria
- All the boards we intend to support should not only compile, but run CDP as expected.
- Compilation should work with Arduino IDE 1.8.19 and Platform IO (when/if the board config is available)

## Part 1

- [x] Create a separate repo/branch?
- [x] Review current boards and select only ones we intend to fully support.
- [x] Refactor boards header files and cdpcfg.h

## Part 2

- [ ] #355
- [x] Test every single board we intend to support: DuckLink, MamaDuck and PapaDuck (depending of the board capabilities) should be tested.
- [x] Review the platform.io ini file to make sure these boards are configured (if available through platform IO)

**Comment by amirna2** [comment]
@krook I added more details for this task. It's a pretty straightforward once we start going down the list above

**Comment by amirna2** [comment]
Note: this task will be on hold until we resolve current build issues found in CDP 3.6.1 when attempting to build non ESP32 boards.

**Comment by amirna2** [comment]
I created a PR we can merge as part of the 4.0.0 integration branch.
Reduced the list of supported boards to:
```
heltec_wifi_lora_32_V2 (lora sx1276)
heltec_wifi_lora_32_V3 (lora sx1262)
ttgo_t_beam_sx1262 (lora sx1262)
heltec_cubecell_board v2 (lora sx1262)
heltec_cubecell_gps (lora sx1262)
rocket scream Mini Ultra Pro v3 (arduino zero SAMD21 core) (lora sx1276)
```

**Comment by krook** [comment]
Looking good. Thanks for leading this @amirna2!

**Comment by amirna2** [comment]
Closed this ticket as the tasks were completed for 4.0.0
